### ISSUE TITLE
may i have a question? 

### ISSUE THREAD

**Issue by wangejay** [tgallice/wit-php-example#2]
i found the fatal error and dont know how to fix it. do you have any idea? Thanks. 
Fatal error: Class 'Tgallice\WitDemo\Command\QuickstartCommand' not found in ... ...

**Comment by tgallice** [comment]
Hello @wangejay. It's weird, I have added an Install section in the README (and move the demo.php to the root folder). Can you tell me if a fresh install following the Install section help you ?

**Comment by wangejay** [comment]
It works!! Thanks.
