### ISSUE TITLE
Path for speech sample does not work

### ISSUE THREAD

**Issue by sgould420** [tgallice/wit-php-example#5]
Following the instructions in README.md  does not work for the speech command example, because the path is wrong.

I think that [line 86 in the instructions](https://github.com/tgallice/wit-php-example/blame/3524fb8f1c021dc19f34883d9af008d0c9188254/README.md#L86) should be: `File path >>> src/sample/sample.mp3` and also [SpeechCommand.php, line 46](https://github.com/tgallice/wit-php-example/blob/3524fb8f1c021dc19f34883d9af008d0c9188254/src/Command/SpeechCommand.php#L46) should just be be: `$file = realpath($file);`

**Comment by tgallice** [comment]
Hi @sgould420 ! Thank to have reporting this. I have fixed the issue.
